[package]
name = "md5sumsum"
version = "0.1.0"
authors = ["Walid LAOUER <walid.chiko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
md5 = "0.7.0"
rayon = "1.1"